services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "2626:8000"
    environment:
      - BOGGLE_DEBUG=False
    volumes:
      - boggle_data:/data
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "2727:80"
    depends_on:
      - backend
    restart: always

volumes:
  boggle_data:
